"""Access and download data from OpenCitations."""

from .api import Backend, get_incoming_citations, get_outgoing_citations
from .client import (
    get_doi_from_omid,
    get_doi_to_omid,
    get_omid_from_doi,
    get_omid_from_pubmed,
    get_omid_to_doi,
    get_omid_to_pubmed,
    get_pubmed_from_omid,
    get_pubmed_to_omid,
)
from .download import (
    ensure_citation_data_csv,
    ensure_citation_data_nt,
    ensure_citation_data_scholix,
    ensure_metadata_csv,
    ensure_metadata_kubernetes,
    ensure_metadata_rdf,
    ensure_provenance_data_csv,
    ensure_provenance_data_nt,
    ensure_provenance_rdf,
    ensure_source_csv,
    ensure_source_nt,
)
from .json_api_client import (
    get_articles,
    get_articles_for_author,
    get_articles_for_editor,
    get_incoming_citations_from_api,
    get_outgoing_citations_from_api,
)
from .models import Citation, CitationReturnType, Person, Publisher, Venue, Work

__all__ = [
    "Backend",
    "Citation",
    "CitationReturnType",
    "Person",
    "Publisher",
    "Venue",
    "Work",
    "ensure_citation_data_csv",
    "ensure_citation_data_nt",
    "ensure_citation_data_scholix",
    "ensure_metadata_csv",
    "ensure_metadata_kubernetes",
    "ensure_metadata_rdf",
    "ensure_provenance_data_csv",
    "ensure_provenance_data_nt",
    "ensure_provenance_rdf",
    "ensure_source_csv",
    "ensure_source_nt",
    "get_articles",
    "get_articles_for_author",
    "get_articles_for_editor",
    "get_doi_from_omid",
    "get_doi_to_omid",
    "get_incoming_citations",
    "get_incoming_citations_from_api",
    "get_omid_from_doi",
    "get_omid_from_pubmed",
    "get_omid_to_doi",
    "get_omid_to_pubmed",
    "get_outgoing_citations",
    "get_outgoing_citations_from_api",
    "get_pubmed_from_omid",
    "get_pubmed_to_omid",
]
